### ISSUE TITLE
Usage with DynamicImage or ImageBuffer

### ISSUE THREAD

**Issue by decipher3114** [awxkee/libblur#1]
I am using this to add blur to my image. I converted the Dynamic Image into bytes but didn't know how to calculate stride. Thus, either provide a guide to calculate the values or implement a function that automatically parse the values from the passed image.

**Comment by awxkee** [comment]
I thought stride is documented. It is count of color components per row. It is not possible to parse this if you're using different alignment. If you're not then stride = width * color components per pixel, if it is RGB image then stride = width *3, if it is RGBA stride = width * 4
