### ISSUE TITLE
Request for Grayscale (Single Channel) Gaussian Blur Support

### ISSUE THREAD

**Issue by giantpand2000** [awxkee/libblur#2]
Hello,

First of all, thank you for providing such a useful library!

Currently, `libblur` supports Gaussian blur for images with 3 or 4 channels, as indicated by the `FastBlurChannels` enum:

```rust
#[repr(C)]
pub enum FastBlurChannels {
    Channels3 = 3,
    Channels4 = 4,
}
```

However, I often work with grayscale images which only have a single channel. It would be incredibly helpful if `libblur` could support Gaussian blur for single channel (grayscale) images as well.

Would it be possible to extend the `FastBlurChannels` enum and the underlying implementation to support single channel images?

Thank you for considering this feature request!

**Comment by awxkee** [comment]
Hi, 
Try version `0.13.0`, support of planes has been added

**Comment by giantpand2000** [comment]
Thank you for adding support for planar images in version 0.13.0. I appreciate your prompt response to my feature request and look forward to testing the new functionality.
