### ISSUE TITLE
Why is the number of threads limited to 12?

### ISSUE THREAD

**Issue by virtualritz** [awxkee/libblur#4]
I'm asking since the headless renderer for my VFX compositing system will often run on 32 or 64 core machines and the images are typically at least 4k. I.e. at 256x256 sized blocks that's ~160 blocks for a 16:9 image. Why limit this to 12 cores?
OIIO uses all threads=cores by default and they do get maxed out on my 24 core desktop when processing 4k images.

And on that note: would you accept a PR that allows a number on `ThreadingPolicy::Adaptive` that means: reserve this many cores from all available? Or alternatively (to not break the API) `ThreadingPolicy::AdaptiveReserve`.

I.e. on a 32 core system. `Adaptive(0)` = 32 cores but `Adaptive(3)` = 29 cores (32-3). This is very useful when running multithreaded code on a DCC app where the user interacts with a UI or the like.
When the CPU is maxed out the system can be come unresponsive and sometimes even the mouse cursor does not move. Reserving/not using 1--2 cores usually solves this.

**Comment by awxkee** [comment]
Actually this is pretty good question.
But in my common practice `just increase amount of threads` is not adding any gains when threads count goes somewhere up to 10-12.
Sure, I can accept PRs :)
Also it will be quite interesting if you'll launch benchmark on such machine just to fill my curiousity :)

**Comment by virtualritz** [comment]
On that note, I would also rename `get_threads_count()` to `thread_count()` in my PR.

The `get_` prefix is against [Rust API naming policies](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter) and `threads_count` is wrong English, the counted thing is always singular. :grin:.

 Is that ok?

**Comment by awxkee** [comment]
That’s fine

**Comment by virtualritz** [comment]
See #6.

**Comment by awxkee** [comment]
I believe this is resolved.
